# .streamlit/secrets.toml

STRAVA_CLIENT_ID = 174191
STRAVA_CLIENT_SECRET = "98bf6ef89e262ed9effb825925c7bf1167a93afb"

MAPBOX_API_KEY = "pk.eyJ1IjoiZ3VpbGxlbWxsdWNpYSIsImEiOiJjbWVyOW11dzkwNHdiMnBzandyb2kwZ3I1In0.LsbC75yH54RQtoZ16LT6Rg"
